tunnel: e22139d1-353c-4e6b-b260-e143d3e4c9ee
credentials-files: /root/.cloudflared/e22139d1-353c-4e6b-b260-e143d3e4c9ee.json
origincert: /root/.cloudflared/cert.pem

ingress:
  - hostname: lmdev.balmos.org
    service: http://localhost:80
  - hostname: lmdev-cs.balmos.org
    service: http://localhost:8080
  - hostname: lmdev-ssh.balmos.org
    service: ssh://localhost:22
  - service: http_status:404
