# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable"

[redis]
url="redis://redis:6379"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"

[application_server.api]
public_host="application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
# Set by APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET in docker-compose.yml
#jwt_secret=""
