version: "3"

services:

  ################
  ## Chirpstack ##
  ################
  network-server:
    image: docker.io/chirpstack/chirpstack-network-server:3.15
    restart: unless-stopped
    volumes:
      - ./network-server:/etc/chirpstack-network-server:z
    depends_on:
      - postgresql
      - mosquitto
      - redis

  application-server:
    image: docker.io/chirpstack/chirpstack-application-server:3.17
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # Generate with `openssl rand -base64 32`
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=W2WxgQTTrl0YSD2SgoRNMzUl0521hn3vCmL2YL/wH4M=
    volumes:
      - ./application-server:/etc/chirpstack-application-server:z
    depends_on:
      - network-server

  postgresql:
    image: docker.io/postgres:9.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgresql-initdb.d:/docker-entrypoint-initdb.d:z
      - cs-postgres:/var/lib/postgresql/data

  redis:
    image: docker.io/redis:5-alpine
    restart: unless-stopped
    volumes:
      - cs-redis:/data:z

  mosquitto:
    image: docker.io/eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 10.100.0.1:1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:z

  #################
  ## ThingsBoard ##
  #################
  thingsboard:
    image: docker.io/thingsboard/tb-postgres:3.3.3
    restart: unless-stopped
    ports:
      - "80:9090"
      - "1887:1883"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard

volumes:
  tb-data:
  tb-logs:
  cs-postgres:
  cs-redis:
